# Generated by Django 4.0.6 on 2022-07-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0003_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Exam_month',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
