# Generated by Django 4.0.6 on 2022-07-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0004_student_exam_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Exam_month',
            field=models.CharField(choices=[('January', 'Jan'), ('February', 'Feb'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'Jun'), ('July', 'July'), ('August', 'Aug'), ('September', 'Sup'), ('October', 'Oct'), ('November', 'Nov'), ('December', 'Dec')], max_length=20),
        ),
    ]
