# Generated by Django 4.0.6 on 2022-07-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0005_alter_student_exam_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
